### ISSUE TITLE
I get  NoMethodError: undefined method `[]' for nil:NilClass

### ISSUE THREAD

**Issue by ghost** [Dariusch/plenty_client#4]
I ve tried your gem from irb, inputting login data there.
The Item with ID 103 exists, but 
trying to fetch IT, it goes
`NoMethodError: undefined method `[]' for nil:NilClass
	from /home/cartasu/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/plenty_client-0.1.0/lib/plenty_client/request.rb:71:in `login_check'
	from /home/cartasu/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/plenty_client-0.1.0/lib/plenty_client/request.rb:11:in `request'
	from /home/cartasu/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/plenty_client-0.1.0/lib/plenty_client/request.rb:50:in `get'
	from /home/cartasu/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/plenty_client-0.1.0/lib/plenty_client/item.rb:20:in `find'
	from (irb):30
	from /home/cartasu/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/railties-4.2.10/lib/rails/commands/console.rb:110:in `start'
	from /home/cartasu/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/railties-4.2.10/lib/rails/commands/console.rb:9:in `start'
	from /home/cartasu/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/railties-4.2.10/lib/rails/commands/commands_tasks.rb:68:in `console'
	from /home/cartasu/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/railties-4.2.10/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
	from /home/cartasu/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/railties-4.2.10/lib/rails/commands.rb:17:in `<top (required)>'
	from bin/rails:4:in `require'
	from bin/rails:4:in `<main>'`
`

**Comment by ghost** [comment]
OK... missing dependencies
